### ISSUE TITLE
BasicAuthentication

### ISSUE THREAD

**Issue by nk111** [mattwendels/tfs-build-notifications#3]
Somehow i'm not able to add a connection to an on premise TFS 2018 which has BasicAuthentication turned off. The error msg is "not authorized". 

It's suggested to keep this off by Microsoft. Am i missing something?

I managed to add a server connection to this server by switching to VSO-Mode and providing a personal access token. But then i get a nullpointerexception when i try to add a build:

Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. bei Tfs.BuildNotifications.Core.Clients.TfsApiClient.GetBuildDefinitions(Connection connection, String projectName) in ...\tfs-build-notifications\Tfs.BuildNotifications\Tfs.BuildNotifications.Core\Clients\TfsApiClient.cs:Zeile 61

Any suggestion?

**Comment by mattwendels** [comment]
Hi, not sure how you're accounts are set up on your on-premise TFS... we are using AD, so we're logging in with Windows Log on credentials. Haven't had to enable BasicAuth as far as I'm aware.

Re the error - I can't repro but can you send me your log file (tfs.buildnotifications.log in the working dir) and I'll take a look (preferrably in English if poss!)

**Comment by nk111** [comment]
BasicAuth is used because of this line (96) in TfsApiClient.cs:
client.Authenticator = new HttpBasicAuthenticator(credentials.UserName, credentials.Password);

In our case this leads to errors because BasicAuth is not enabled on the server.

I had to change this to:

client.Authenticator = new NtlmAuthenticator(credentials.UserName, credentials.Password);

then everything is fine.

**Comment by mattwendels** [comment]
Ah yes of course. Good spot!

**Comment by nk111** [comment]
After i could connect to our "on premise" tfs now i still got the null pointer exception mentioned above when trying to add builds.

I found out it's because of some XAML build definitions we are having listed. Those seem to have no links so the following code chrashes:

foreach (var item in result)
            {
                    buildDefinitions.Add(new BuildDefinition
                    {
                        Id = item.Id,
                        Name = item.Name,
                        Url = item.Links.Web.Url
                    });
            }

so we had to check for null:

foreach (var item in result)
            {
                if (item.Links != null)
                {
                    buildDefinitions.Add(new BuildDefinition
                    {
                        Id = item.Id,
                        Name = item.Name,
                        Url = item.Links.Web.Url
                    });
                }
            }

**Comment by jespersh** [comment]
> BasicAuth is used because of this line (96) in TfsApiClient.cs:
> client.Authenticator = new HttpBasicAuthenticator(credentials.UserName, credentials.Password);
> 
> In our case this leads to errors because BasicAuth is not enabled on the server.
> 
> I had to change this to:
> 
> client.Authenticator = new NtlmAuthenticator(credentials.UserName, credentials.Password);
> 
> then everything is fine.

Can confirm this change is require in some (probably not all) cases. Otherwise getting an Unauthorized exception

**Comment by mattwendels** [comment]
@jespersh - yes, should be all that's needed. When I created this we had basic auth enabled on our (on-prem) TFS server. Most people don't have/want that, so I've just updated the code to use the NtlmAuthenticator by default. You should be able to grab the installer and it should all just work out the box now (hopefully!)

Cheers
