### ISSUE TITLE
tfs-build-notifications does not start on windows 7

### ISSUE THREAD

**Issue by Giois93** [mattwendels/tfs-build-notifications#4]
tfs-build-notifications throws and exception when launched on my windows 7 pro sp1.

Missing Windows.UI.Notifications.ToastNotificationManager
![cattura](https://user-images.githubusercontent.com/10637435/38923676-746aec8e-42fb-11e8-9da0-90858543e3d3.PNG)

![cattura1](https://user-images.githubusercontent.com/10637435/38923762-9762d864-42fb-11e8-8f7a-6db27c979e87.PNG)

I suppose Windows 7 does not support Toast Notification.
Is tfs-build-notifications only compatible with later versions or this is only related to missing component?

**Comment by mattwendels** [comment]
Hi, I've committed a change to fall back to tool tip/balloon notifications for any other OS than Windows 10 (can't guarantee that the correct meta data files are there on any other OS that Win10). I've tested on Win7 and WinServ 2008 machines and it now works for me, using the tool tip notifications. Hope this helps.
